## Example Config file
BaseURL: "http://localhost:1313/"
theme: "terminalCV"
title: "terminalCV"

params:
  description: "4s3ti cv terminal format"
  prompt: "guest"
  promptColor: lightgreen
  promptSimbols: ":>"
  promptSimbolsColor: lightgreen
# startxLocation: https://example.com
# hideSocialName: true
# exitLocation: 'about:blank'
# hidesource: false
  greeting: | 
    Welcome to the Insight Engine. 
        
        Your gateway to the Architect's digital anthology. 
    
            Type 'help' to navigate the command matrix.

  whois: 
      name: "Dencho Dennis Denchyaknow"
      profession: "Unity Developer/Programmer"
      location: "MetaVerse"
      email: "Denchyaknow@gmail.com"
      homelink: "https://Dencho.dev"
      description: |
              I am a Unity Developer and Programmer with a passion for creating interactive experiences. 
              I have a background in Computer Science and a love for all things tech. 
              I am always looking for new opportunities to learn and grow as a developer.

  social:
    ## IF you want to keep them aligned just add spaces
    - name: "github"
      url: "  https://github.com/denchyaknow"
#    - name: "facebook"
#      url: "        https://facebook.com"
#    - name: "myspace"
#      url: "         https://myspace.com"
#    - name: "hi5"
#      url: "             https://www.hi5.com"
#    - name: "instagram"
#      url: "       https://instagram.com"
    - name: "Another social"
      url: "  https://anothersocial.com"

  workexp:
    - jobTitle: Job With Red Title
      color: red
      company: '-' 
      location: somewhere
      date: August 2010 - Present
      description: Some description about this red title job

    - jobTitle: Job with purple title
      color: purple
      company: '-'
      location: somewhere elese
      date: July 2000  - July 2010
      description: Some description about this purple job

    - jobTitle: Job with default color title
      company: '-'
      location: anywhere
      date: July 2008 - 2010
      description: Description about this default color job

  education:
   - courseName: Red Color training
     color: red
     date: June 2019 - July 2019
     description: Descrption about red color trianing

   - courseName: Default color training
     date: Sept 2004 - Jun 2008
     #description: There is no need for description

  skills:
    - name: Skill 1
      percentage: 90
      Description: you can add a description

    - name: Skill 2
      percentage: 30
      #description: or you can leave it comented   

    - name: Skill 3
      color: blue
      percentage: 50
      description: Skill names can have colors too

  softskills:
    - name: SoftSkill 1
      color: red
      percentage: 80
      #description:

    - name:  SoftSkill 2
      #color: 
      percentage: 90
      description: Description

  languages:
    - name: English
      color: Blue
      percentage: 50
      #description: 

    - name: Gibberish
      percentage: 100
      description: pasghettipigglywiggly


  projects:
    - title: Project Red
      color: red
      date: since 2019
      link: https://example.com
      description: Describing red stuff

    - title: Project Blue
      color: blue
      date: since 2016
      link: https://example.com/blue
      #description: nothing to describe

    - title: Project Default
      date: Since 2017
      link: https://example.com/default
      #description: not there either

  certifications:
  - certName: Example Cert
    company: Example Certifying Company
    date: Date of Completion
    #description: Lorem Ipsum
  
  misc: 
    #commandName: newcommand
    title: "This Section can have a different command name"
    titleColor: teal
    content: |
          Here the title and the content can have different colors
          The content can be multi
          
          line

          And spaces       will be respected as well
          This section will have the default command: misc
          but you can name it something else with the property
          commandName: <String>
          Give it a shot and try and uncomment the line 
          commandName: newcommand
          now instead of misc you can execute the newcommand for this section
          Auto completion will know it too! :D 

    contentColor: orange
